### ISSUE TITLE
[US-01] Simplifying tasks through Discord bot commands

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#1]
**Summary:** As a programmer or regular user, when I detect a task that can be simplified in a bot, I want to be able to create different Discord bots so that I can set commands on them to perform these tasks.

**Goal:** The creation of Discord bots to separate functionality in them.

**Benefit:** In this way, I can make use of the commands configured in the bots, instead of having to perform the tasks manually.

**User profile:** Programmer / regular user.

**Scenario:**
- Given: that I have detected tasks that could be simplified by making use of bots commands,
- When: I create and configure the bots,
- Then: both I and other users can make use of the commands, instead of having to perform these tasks myself.

**Dependencies:**
- None for now.

**Acceptance criteria:**
- Tasks can be automated in bots.
- The user is warned in case of error.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
USs need to describe
1. What kind of user is going to be the client for this. How technical? What kind of device? How fast do they want it?
2. What kind of profit the user is going to obtain. If they don't follow those rules, they're not US, they're simply issues.

**Comment by JJ** [comment]
You also need to *always* be aware of what you want to achieve with the bot. Depending on its purpose, its architecture is going to be totally different.

**Comment by JJ** [comment]
Additionally, you should include in *all* milestones documenting the technical decisions involved. In this specific case, not clear what "creating a bot" might involve, for instance.

**Comment by harvestcore** [comment]
@JJ Done. You can see [this](https://github.com/harvestcore/matroos/milestones) or [this ](https://github.com/harvestcore/tfm-doc/blob/develop/md/planificacion/milestones.md) for more info.

**Comment by JJ** [comment]
Comentarios sobre eso (aunque habría sido conveniente que crearas un PR para poder comentar ahí).
1. En general, todos los milestones tienen que ser un MVP. El 0 dices que no sería un milestone real, sin embargo tiene un MVP: el sistema de CI que sirva para pasar tests al texto que se vaya añadiendo y otras comprobaciones de calidad que se decidan. La infraestructura CI *es* un MVP.
2. Hay un gran hueco entre el 0 y el 1. Los milestones son efectivamente un roadmap, y ser capaz de crear bots después de sólo haber conseguido instalar el CI me parece un gran paso. Tendrás que tener milestones intermedios que incluyan cosas como la modularización general del código del proyecto.
3. El milestone 1 sigue sin ser un MVP. Dices lo que va a hacer, pero no describes *qué* es lo que va a hacer eso. El *qué* es el producto mínimamente viable.

**Comment by harvestcore** [comment]
Continúa la discusión aquí: https://github.com/harvestcore/tfm-doc/pull/3

**Comment by JJ** [comment]
Convendría también que lo siguieras aquí. Tienes que rehacer prácticamente todos los milestones.

**Comment by JJ** [comment]
"Create a bot" sigue sin ser una historia de usuario. Por favor, reformúlala indicando qué beneficio se quiere obtener creando un bot. Por ejemplo, "quiero enviar un mensaje al canal cada cierto tiempo". Las historias de usuario son verdaderas historias de usuario, porque si no tienes ningún usuario en mente puedes intentar hacer todos para todos y no contentar a nadie.
En concreto, si se trata de "enviar cosas periódicamente" (que no lo sé) puede que no necesites más que reusar algún bot existente.
