### ISSUE TITLE
[US-11] Get deployment status

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#11]
**Summary:** As an administrator user I want to be able to know the status of the bots that are currently deployed in the system.

**Goal:** Get details about the workers that are running and about the bots that are deployed in the workers.

**Benefit:** See which bots are active and which are not, for system monitoring purposes.

**User profile:** Administrator.

**Scenario:**
- Given: that I want to know the status of the bots that are currently deployed,
- When: I request that information to the system,
- Then: the system sends back all the information.

**Functional notes:**
- The data should not include bot configuration.
- The data should include information about the workers that are running the Discord bots.

**Technical notes:**
Data to be returned:
- []workers: []Worker, [req]. All the workers that are available in the system.

- Worker:
  - id: UUID [req]. Unique worker identifier.
  - uptime: DateTime. The uptime time of the worker.
  - location: str. The URL where the worker is located.
  - []bots: []Bot. The bots that are deployed in the worker.

- Bot:
  - id: UUID [req]. Unique bot identifier.
  - uptime: DateTime. The uptime time of the bot.
  - ...

**Dependencies:**
- [x] #12 
- [x] https://github.com/harvestcore/matroos/issues/1
- [x] https://github.com/harvestcore/matroos/issues/3
- [x] https://github.com/harvestcore/matroos/issues/5
- [x] https://github.com/harvestcore/matroos/issues/7
- [x] https://github.com/harvestcore/matroos/issues/9
- [x] https://github.com/harvestcore/matroos/issues/10

**Follow-up tasks:**
- None for now.

**Acceptance criteria:**
- The data is returned correctly.
- The user is warned in case of an error when fetching the data.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
User stories always describe the profit the user wants, and always described in the problem domain. "Get deployment status" describes no profit, but an action that you need to perform so that the user obtains the profit. But before it should be very clear what's the profit and the problem you want to solve.

**Comment by harvestcore** [comment]
Not a US
