### ISSUE TITLE
[DEV] Create the user interface project.

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#16]
**Summary:** Create the user interface project so the development of the next tasks can begin.

**Related tasks:**
- #25

A simple create-react-app sample project should do for now.

**Acceptance criteria:**
- The boilerplate code is removed.

**Comment by JJ** [comment]
Every task must be
* A problem that needs a solution: an error needs to be fixed, an user-facing problem that needs decisiones. There's never a task that says "create this", even less so with a specific framework. Creating this (or a totally different thing) needs to be a decision that's justified in terms of the current project, and solves a problem, and that does so provably; there's a test that certifies that the solution *really* solves the problem. If there's no problem, there's no way to test if it's been solved. And if there's no test, you simply can't affirm that the code does what it's supposed to do.
* Related to a US. Code is written *only* to advance an US, and only to get to a minimally viable product. If it does not, then you are not advancing in the solution of the problem.

Please remember also #24. The milestone this is assigned to is a module of the solution (and we don't even know if we're going to need a frontend to solve the problem)

**Comment by harvestcore** [comment]
@JJ You're 100% right.

This issue will be refactored asap.
