### ISSUE TITLE
[US-02] Get data from a bot

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#2]
**Summary:** As an admin user, I want to see the details of the Discord bots created in the system, so that I can see their characteristics and settings.

**Goal:** Obtain all the data of a specific bot or of all the bots created in the system to consult their characteristics and configuration.

**Benefit:** Consult the unique and specific configuration of each of the bots.

**User profile:** Administrator.

**Scenario:**
- Given: that I want to get all the data of the bots created in the system,
- When: I perform a request to the system for that,
- Then: the system returns all the data.

**Functional notes:**
- Get the data of all bots is allowed.
- Get the data of a single bot is allowed.

**Technical notes:**
Data needed to query a single bot:
- id: UUID [req]. Unique identifier for the bot.

**Dependencies:**
- [x] #12 

**Follow-up tasks:**
- None for now.

**Acceptance criteria:**
- All the data related to a bot is returned.
- The user is warned in case of an error when querying bots data.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
This is not a user story. A user story needs to be expressed from the point of view of the final user, and must be in the problem domain. This is possibly a task that will be needed to satisfy that need or solve that problem, but it's not the only possible. If you start writing tasks before USs, you run the risk of committing yourself to tasks that don't solve any problem.

**Comment by harvestcore** [comment]
Self note: Clarify the information in this US. Make sure that this US is really a US, otherwise convert it to a task.

**Comment by harvestcore** [comment]
Not a US
