### ISSUE TITLE
Milestones need to be a minimally viable product

### ISSUE THREAD

**Issue by JJ** [harvestcore/matroos#24]
"Worker" and "Backend" are functional divisions, they are not consecutive steps in the creation of a product.
Besides, milestones are not grouping of tasks, they are effectively milestones in a road, something you need to reach before you go ahead to the next one. So, "Worker" and "Backend" can *never* be developed at the same time.

**Comment by harvestcore** [comment]
My bad, I'll change the naming, scope, and "order" of the milestones asap.

**Comment by harvestcore** [comment]
This should be resolved by now.

**Comment by JJ** [comment]
Please remember that a milestone has to describe the deliverable, as in "Environment and CI set up" not a task, as in "Set this up"

**Comment by JJ** [comment]
1. "Creation of a bot" is a task, not a deliverable. Also, is this "minimal"?
2. Not clear what you want to achieve here. Are you talking about actually deploying them? Or scripting to deploy them?
3. API for what? Please try and be more descriptive, up to and including saying what's the MVP you'll be delivering here.
4. Please clarify is you want the tools for doing this, or actually doing it. Also not clear what end user you have in mind
5. Same as above
6. This is a component, not a minimally viable product.

Please bear in mind that a list of milestones is a roadmap that allows you to organize your work incrementally. They should roughly take the same time. It's your turn to organize priorities so that more prioritary MVPs go before less prioritary. Is cloud deployment more prioritary than UI? Do you need *both* container deployment *and* cloud deployment? Is the API less important than "deploying bots in workers"?

**Comment by harvestcore** [comment]
@JJ Milestones should be more clear now. I've added extra information and extra documentation. See: https://github.com/harvestcore/tfm-doc/blob/develop/md/planificacion/milestones.md

**Comment by JJ** [comment]
Lo mejor es que pongas eso en un PR, y lo discutimos ahí.

**Comment by harvestcore** [comment]
Continúa la discusión aquí: https://github.com/harvestcore/tfm-doc/pull/3

**Comment by harvestcore** [comment]
Closed here: https://github.com/harvestcore/tfm-doc/pull/3
