### ISSUE TITLE
[US-05] User interface

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#25]
**Summary:** As a programmer or regular user, I want the display of data in the user interface to be simple so that I can easily understand how to create bots and configure them.

**Goal:** The user interface should allow less experienced users to easily create and configure bots.

**Benefit:** Any user, with more or less computer knowledge, can create and configure Discord bots.

**User profile:** Administrator / regular user.

**Scenario:**
- Given: that I want to manage the Discord bots,
- When: I access the graphical user interface,
- Then: the system allows me to perform all bot administration tasks easily.

**Dependencies:**
- [x] #1 
- [x] #3 
- [x] #5 
- [x] #7 

**Acceptance criteria:**
- The tasks of managing bots and commands are simplified (in complexity and time) in the interface.
- The user is warned in the event of an error.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
Again, users don't know technical details, and user stories shouldn't be about concrete implementations. In this case, an user wants to "create, configure, deploy and know the status of the Discord bots.". Doing so by a GUI or some other way is up to the developer, and it's possible to go over different minimal viable products until something totally satisfactory is achieved.
If you describe the end product, you run the risk of tightly coupling everything to that end product, and then forgetting the layered design, corresponding to agile development.

**Comment by harvestcore** [comment]
Self note: Clarify this better in the documentation and user story. Document all research done.

**Comment by JJ** [comment]
Also eliminate the US tag and any information that says this is a tag. Besides, any issue needs to present a problem or challenge, not a solution. It can't say "we need an UI", but what information it will need to convey and present and to whom. Depending on that, it might have different UIs: conversational, graphic, text...

**Comment by JJ** [comment]
The US tag is still here.
