### ISSUE TITLE
[US-02] Edit bots and commands

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#3]
**Summary:** As a programmer or regular user I want to be able to change the functionality of the bots, as I may sometimes need to expand or reduce their commands, or change what these commands do. 

**Goal:** Allow adding or removing commands from bots, and their configuration.

**Benefit:** I may want to add new commands to a bot or remove them, so I can do that.

**User profile:** Programmer / regular user.

**Scenario:**
- Given: that needs are likely to change,
- When: I modify the bots and commands,
- Then: I and other users have access to the new changes in the bots.

**Dependencies:**
- [x] #1

**Acceptance criteria:**
- Bots and commands can be updated.
- The user is warned in case of error.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
Also a task, not something the administrator needs to do.

**Comment by harvestcore** [comment]
@JJ By "administrator user" I mean the person who will create and configure the bots (see [this](https://github.com/harvestcore/tfm-doc/blob/develop/md/analisis/analisis.md#descripci%C3%B3n-de-actores)). In this case, this user story refers to the configuration of these bots (e.g.: adding a new command to the bot).

**Comment by harvestcore** [comment]
Self note: Clarify the information in this US.
