### ISSUE TITLE
[BUG] The milestones need to follow a logical progression, progressively complex minimally viable products.

### ISSUE THREAD

**Issue by JJ** [harvestcore/matroos#35]
1. There are too many milestones. Generally, you'll plan ahead only 2 or 3 milestones.
2. They are not logically ordered. Normally they follow the progression infrastructure - data structures - business logic - API... Data storage will be last, and only if absolutely needed.
3. They still describe tasks, and not products. "Setup environment tests and CI" should be "CI is ready to test this and that". "Data Store" is a functional part, not even a product. "Commands management" would need to describe the commands that it actually manages... And on on.

**Comment by harvestcore** [comment]
1) Q: Is it wrong to define "all" the milestones from start? To me it seems logical to define the whole set of milestones from the beginning, and then (if needed) add more details to them, or even skip/remove a milestone.

2) Indeed, now that I think the order again... it is not the most logical one. Does this order make sense to you?
- 00 - Env configuration, CI and so on.
- 01 - Bots management.
- 02 - Commands management.
- 03 - Run bots on workers.
- 04 - API Rest
- 05 - Deploy in Docker containers
- 06 - Database integration
- 07 - User interface
- 08 - Deploy in cloud services
3) My b, I'll try to reescribe all of them the proper way

**Comment by JJ** [comment]
Please remember that every milestone needs to include the previous one. For instance "User interface" should rather be "prototype application with an user interface"

**Comment by harvestcore** [comment]
Yes, I bear that in mind. The headings in the previous comment are very brief, just to outline the structure, I will include more details in the final version.

**Comment by JJ** [comment]
OK, this one will be closed when the PR in the other repo is merged, and then development of the report will be moved here, right?

**Comment by harvestcore** [comment]
@jj Yep, that is right.
