### ISSUE TITLE
Plantea claramente el problema que quieres resolver

### ISSUE THREAD

**Issue by JJ** [harvestcore/matroos#36]
La ingeniería del software resuelve problemas, y es esencial entender cuál es el problema. No puedes empezar diciendo qué solución vas a dar, tienes que comenzar por plantear claramente (y de forma concisa) el problema a resolver.

https://github.com/harvestcore/tfm-doc/blob/ef68d068303b79d28ba17971d4624e668a435229/md/introduccion/introduccion.md?plain=1#L5

**Comment by harvestcore** [comment]
Gracias por echarle un ojo, JJ. La verdad es que estaba planteado terriblemente mal, de manera muy vaga. Ahora debería estar mejor.
