### ISSUE TITLE
Plantea claramente los objetivos del trabajo

### ISSUE THREAD

**Issue by JJ** [harvestcore/matroos#37]
Recuerda el [documento sobre cómo plantear los objetivos](https://jjmerelo.medium.com/c%C3%B3mo-formular-buenos-objetivos-en-un-trabajo-7e68abf10028) para plantear claramente los objetivos aquí. Puedes ponerlos en el README, o simplemente empezar a escribir la memoria.

**Comment by harvestcore** [comment]
Les he dado otra vuelta y creo que ya cumplen el "EMA".
