### ISSUE TITLE
[US-04] Delete a bot

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#4]
**Summary:** As an administrator user I want to be able to delete a bot and all its configuration.

**Goal:** The removal of bots.

**Benefit:** When a bot is no longer needed, it can be removed.

**User profile:** Administrator.

**Scenario:**
- Given: that I want to delete a bot,
- When: I provide the identifier of the bot I want to delete,
- Then: the system deletes the bot and all its configuration associated.

**Functional notes:**
- In case a bot is deployed, its deployment must be canceled and then the bot must be removed.

**Technical notes:**
Data needed to get the bot to be deleted:
- id: UUID [req]. Unique identifier for the bot.

**Dependencies:**
- [x] #12 
- [x] https://github.com/harvestcore/matroos/issues/1

**Follow-up tasks:**
- None for now.

**Acceptance criteria:**
- The bot is deleted correctly.
- The user is warned in case of an error when deleting a bot.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
¿Qué beneficio para el usuario conlleva borrar un bot?

**Comment by harvestcore** [comment]
Not a US
