### ISSUE TITLE
[US-03] Expandable command set

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#5]
**Summary:** As a programmer I want to have a set of predefined commands that can be expanded and then create customized commands from them.

**Goal:** Have an expandable set of predefined commands.

**Benefit:** When I need to create a new type of command for specific functionality that is not available in the current commands, I can program this functionality and then make use of it to create custom commands.

**User profile:** Administrator.

**Scenario:**
- Given: I want to have a number of predefined commands available,
- When: I need commands with specific new functionality,
- Then: the system allows me to implement them and use them later.

**Dependencies:**
- None for now.

**Acceptance criteria:**
- Predefined commands can be implemented correctly.
- The user is warned in case of error.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
Does not look like a US either. It's a task.
