### ISSUE TITLE
[BUG] La introducción tiene que seguir un formato estándar que incluye la respuesta a una serie de preguntas.

### ISSUE THREAD

**Issue by JJ** [harvestcore/matroos#59]
**Describe the bug**

La introducción es "¡Se va a acabar el mundo! Pero no hay que preocuparse, porque en este TFM voy a hacer un app para que no se acabe"

La introducción tiene que contestar a las preguntas

* [ ] ¿Qué problema hay en el mundo que quiero resolver?
* [ ] ¿Por qué quiero resolver este problema, y qué probabilidades tengo de hacerlo en este TFM?
* [ ] ¿Para quién quiero resolverlo en concreto y por qué para este grupo y no otros?
* [ ] ¿Cómo pienso sacar dinero de todo ello, aunque sea para pagar el hosting? O si no hay hosting necesario, qué posibilidades de monetización puede tener la biblioteca en sí o servicios basados en la misma.

Esto tiene que hacerse *antes que cualquier otra cosa*. Se debe tratar de entender qué problema se quiere resolver, antes de pasar a explicar el contexto y posibles soluciones (existentes, y la que queremos hacer).

Por favor, crea un PR específicamente para este issue porque bloquea el desarrollo del resto de la memoria.

**Comment by harvestcore** [comment]
La introducción la reescribí teniendo en cuenta esas cuatro preguntas, y creo que están respondidas en [este PR](https://github.com/harvestcore/matroos/pull/57).

> ¿Qué problema hay en el mundo que quiero resolver?

https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L9
https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L11

> ¿Por qué quiero resolver este problema, y qué probabilidades tengo de hacerlo en este TFM?

https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L7
https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L13
https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L26


>  ¿Para quién quiero resolverlo en concreto y por qué para este grupo y no otros?

https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L15
https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L18
https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L19

> ¿Cómo pienso sacar dinero de todo ello, aunque sea para pagar el hosting?

https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L22

**Comment by JJ** [comment]
> La introducción la reescribí teniendo en cuenta esas cuatro preguntas, y creo que están respondidas en [este PR](https://github.com/harvestcore/matroos/pull/57).
> 
> > ¿Qué problema hay en el mundo que quiero resolver?
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L9
> 

Lo siento, pero esto parece indicar que el problema son los bots. Y tampoco está al principio de la introducción. Si "los bots" son un problema, entonces tienes que resolver el problema de "los bots". Y eso queda un poco fuera de ámbito para un TFM.

> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L11

Si el problema es "la creación de bots", tienes que aclarar para quién, y en función de eso, elegir la solución: una biblioteca (pero tendrá que ser en un lenguaje popular, o no resolverás el problema más que de una pequeña parte), un lenguaje de descripción de bots (que resolverá el problema de más gente, posiblemente, al tener un modelo abstracto de más alto nivel) o un programa (que tendrá que ser de pago, claro, porque un servidor no se paga solo). Una vez más, describir el problema, la clientela, como añades valor para las mismas, es esencial para poder crear una solución que realmente sea un TFM viable.

> 
> > ¿Por qué quiero resolver este problema, y qué probabilidades tengo de hacerlo en este TFM?
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L7

Una vez más, quieres resolver "los bots" y, una vez más, eso no es la expresión de un problema de una persona o colectivo determinado. Tampoco tienes referencias para "el ritmo de crecimiento" ni dices qué usuarios requieren qué funcionalidades de qué bots. Una vez más, la falta de concreción impide entender qué problema estás solucionando, y por tanto impide crear una solución que realmente lo resuelva.
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L13
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L26

Sobre Discord ya te he comentado muchas veces cuál es el problema. 
> 
> > ¿Para quién quiero resolverlo en concreto y por qué para este grupo y no otros?
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L15

¿Dónde está el cliente descrito aquí? 
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L18
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L19

Una vez más, te limitas a describir todos los usuarios posibles. O los usuarios tienen conocimientos de programación, o no lo tienen. REsuelves el problema tanto para uno como para otros. Y además, con una solución única. Para el problema de "los bots". ¿De veras no encuentras un problema en todo esto?

Usuarios sin conocimiento de programación tendrár un problema, y requerirán una solución. Los que tengan conocimiento de programación, una totalmente diferente. Si no te quedas con uno de ellos, y tratas de resolver el problema de uno de ellos, acabarás no resolviendo ningún problema para nadie, me temo.
> 
> > ¿Cómo pienso sacar dinero de todo ello, aunque sea para pagar el hosting?
> 
> https://github.com/harvestcore/matroos/blob/3e18d07e419de0d65f4e71bfe80ac0a09434fc65/doc/tex/secciones/01_introduccion.tex#L22

Esto, como gran parte de lo anterior, ya te lo he comentado en el PR correspondiente. Por favor, trata de hacer caso a lo que te comento para poder avanzar.
