### ISSUE TITLE
[US-06] Get data from a command

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#6]
**Summary:** As an administrator user I want to consult the details of the commands created in the system.

**Goal:** Get all data for a particular command or for all commands created in the system.

**Benefit:** Consult the unique and specific configuration of each of the commands.

**User profile:** Administrator.

**Scenario:**
- Given: that I want to get all the data of the commands created in the system,
- When: I perform a request to the system for that,
- Then: the system returns all the command's data.

**Functional notes:**
- Get the data of all commands is allowed.
- Get the data of a single command is allowed.

**Technical notes:**
Data needed to query a single command:
- id: UUID [req]. Unique identifier for the command.

**Dependencies:**
- [x] #12 
- [x] https://github.com/harvestcore/matroos/issues/5

**Follow-up tasks:**
- None for now.

**Acceptance criteria:**
- All the data related to a command is returned.
- The user is warned in case of an error when querying commands data.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
Definitely not something an user want.

**Comment by harvestcore** [comment]
Not a US
