### ISSUE TITLE
[US-09] Deploy bot

### ISSUE THREAD

**Issue by harvestcore** [harvestcore/matroos#9]
**Summary:** As an administrator user I want to be able to run the Discord bots that I have created and configured on the system in order to be able to use the commands available on the Discord servers.

**Goal:** Deploy bots in workers so that they can be used from Discord servers.

**Benefit:** Running bots allows commands to be made available on Discord servers to users (once the bots are added to those servers).

**User profile:** Administrator.

**Scenario:**
- Given: that I want to deploy a Discord bot so it can be used by users in Discord channels,
- When: I provide the identifier of the bot I want to deploy,
- Then: the system deploys the bot automatically.

**Functional notes:**
- A bot cannot be deployed multiple times.
- Deploying a bot with no commands configured is not allowed.

**Technical notes:**
Data needed to get the bot deployed:
- id: UUID [req]. Unique identifier for the bot.

**Dependencies:**
- [x] #12 
- [x] https://github.com/harvestcore/matroos/issues/1
- [x] https://github.com/harvestcore/matroos/issues/3
- [x] https://github.com/harvestcore/matroos/issues/5
- [x] https://github.com/harvestcore/matroos/issues/7

**Follow-up tasks:**
- None for now.

**Acceptance criteria:**
- The bot is deployed correctly.
- The user is warned in case of an error when deploying a bot.
- Unit/Integration tests are added if possible.

**Comment by JJ** [comment]
A US needs to provide some benefit to the user, and is always described in the problem domain. You can't say "deploy bot", but what you want to deploy the bot for and in which circumstances. Then different issues will need to specify what you mean exactly by deploy, and what kind of technical tradeoffs it implies.
Also, US need to have a number.

**Comment by harvestcore** [comment]
Not a US
